is_particle_exp: True
sampler:
  _target_: vgs.models.vgsampler.ValueGradientSampler
  value:
    _target_: vgs.models.modules.invariant_wrapper
    n_particles: 4
    n_dim: 2
    net:
      _target_: vgs.models.modules_temb.FCNet_temb
      in_dim: 6 # n_particles * (n_particles - 1) // 2
      out_dim: 1
      hidden_dim: 1024
      t_emb_dim: 1024
  n_step: 30
  sample_shape: [8] # n_particles * n_dim
  s2_schedule: quad
  s2_start: 0.1
  s2_end: 1e-4
  alpha_method: ve
  tau: 1
  ema: 0
  v_lr: 1e-5
  i_lr: 1e-3
  TD_loss: smooth_l1
  D_effective: 6 # (n_particles-1) * n_dim
  scale_with_D: True 


buffer:
  n_update: 3


energy_model:
  _target_: vgs.energy.DW4.MultiDoubleWellPotential
  data_path: vgs/particle_data/DW4/val_DW4_rerun.npy

training:
  n_iter: 3000
  batch_size: 512
  save_iter: 300
  log_iter: 50
  n_eval: 2e3

off_policy:
  noise_scale: 1.2